CREATE TABLE IF NOT EXISTS article (id IDENTITY NOT NULL PRIMARY KEY, art_id INTEGER, name VARCHAR(100), stock INTEGER);

CREATE TABLE IF NOT EXISTS product (id IDENTITY NOT NULL PRIMARY KEY, name VARCHAR(100));

CREATE TABLE IF NOT EXISTS product_article (id IDENTITY NOT NULL PRIMARY KEY, prod_id INTEGER, art_id INTEGER, amount_of INTEGER,
FOREIGN KEY (prod_id) REFERENCES product(id),
FOREIGN KEY (art_id) REFERENCES article(art_id));